### ISSUE TITLE
Prototype Deployment Frequency data collection

### ISSUE THREAD

**Issue by yusufscott** [liatrio/o11y-demo#12]
Create a means to collect the deployment events, and store them. 

Required data:
- Deployments with timestamps

```[tasklist]
### Tasks
- [ ] Pull the required data
- [ ] Create a table for the log data
```

**Comment by yusufscott** [comment]
- Investigate GitHub app to webhook even receiver
- Look into webhook auth to be able to send to local instance

**Comment by adrielp** [comment]
Action item to throw something on the calendar for a tech huddle & demo of what we got so far and where we're heading

**Comment by adrielp** [comment]
Closing this as we've done work to accomplish this.
