### ISSUE TITLE
Prototype Change Failure Rate data collection

### ISSUE THREAD

**Issue by yusufscott** [liatrio/o11y-demo#14]
Collect data for Change Failure Rate, and store it

Required data:
- Deployments
- `incident` issues with timestamps
```[tasklist]
### Tasks
- [ ] Collect data for metric
- [ ] Create data relationships for metric
```

**Comment by adrielp** [comment]
Closing this out as this work has been done as part of the DORA metrics MVP. Future work will be created as needed.
