### ISSUE TITLE
Prototype Time to Restore Service data collection

### ISSUE THREAD

**Issue by yusufscott** [liatrio/o11y-demo#15]
Collect the data for the Time to Restore Service metric.

Required data:
- Issues tagged as `incident` with opening and closing timestamps
- Deployment with timestamp that closes the issue
```[tasklist]
### Tasks
- [ ] Pull data for metric
- [ ] Create table relationships for data
```

**Comment by adrielp** [comment]
Closing this out as this work has been done as part of the DORA metrics MVP. Future work will be created as needed.
