### ISSUE TITLE
Create data pulling mechanism for DORA metrics

### ISSUE THREAD

**Issue by yusufscott** [liatrio/o11y-demo#16]
We will need to investigate how we are going to pull and store the data for the metrics. 

We may be able to utilize some existing means, such as webhooks, or we may want to pull this data with our own GitHub app.

This should result in a means to pull the data, and store it for use in the dashboard.

**Comment by yusufscott** [comment]
Investigate:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/webhookeventreceiver

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/influxdbexporter

**Comment by adrielp** [comment]
Closing this as the final documentation is being prepared and future work is being defined.
