### ISSUE TITLE
Add traces to the o11y demo & show the art of the possible

### ISSUE THREAD

**Issue by adrielp** [liatrio/o11y-demo#6]
# Overview
Having a trace stack integrated into the o11y demo would provide good adoption value. 

## AC
* jaeger is added into the demo
* traces from the collector are emitted to jaeger is visualized into the demo
* documentation is updated

**Comment by densellp** [comment]
I can look into this

**Comment by adrielp** [comment]
Jaeger is already in the demo but may be commented out. Going to close this in favor of other work.
